name: Weekly Update
permissions:
  contents: write
on:
  schedule:
    - cron: '0 7 * * 1' # Mondays 07:00 UTC (~09:00 CET/CEST)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci || npm install

      - name: Run updater
        run: npm run update

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/posts.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: weekly update"
            git push
          fi
